### ISSUE TITLE
Build APK does not work out of the box

### ISSUE THREAD

**Issue by zh4ngx** [babariviere/flutter-nix-hello-world#28]
I get an error with "AAPT2" when I try to run `flutter build apk` after checking out the project. This is on NixOS.

````
Execution failed for task ':app:mergeReleaseResources'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
      > AAPT2 aapt2-7.4.2-8841542-linux Daemon #0: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
      > AAPT2 aapt2-7.4.2-8841542-linux Daemon #1: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
      > AAPT2 aapt2-7.4.2-8841542-linux Daemon #2: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
      > AAPT2 aapt2-7.4.2-8841542-linux Daemon #3: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
      > AAPT2 aapt2-7.4.2-8841542-linux Daemon #6: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
      > AAPT2 aapt2-7.4.2-8841542-linux Daemon #5: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
      > AAPT2 aapt2-7.4.2-8841542-linux Daemon #4: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
      > AAPT2 aapt2-7.4.2-8841542-linux Daemon #7: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
```

**Comment by h4m6urg1r** [comment]
Same here but [this](https://www.reddit.com/r/NixOS/comments/1ab77ht/comment/kjq75jz/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) works for me, and I don't understand why.

**Comment by zh4ngx** [comment]
> Same here but [this](https://www.reddit.com/r/NixOS/comments/1ab77ht/comment/kjq75jz/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) works for me, and I don't understand why.

So the gradle opts line probably needs to point to a `build-tools` version that you have installed
`GRADLE_OPTS = "-Dorg.gradle.project.android.aapt2FromMavenOverride=${androidSdk}/libexec/android-sdk/build-tools/34.0.0/aapt2";
`

`buildToolsVersion = "34.0.0"`

**Comment by zh4ngx** [comment]
Let me give it a try and see if I can narrow it down

**Comment by h4m6urg1r** [comment]
> > Same here but [this](https://www.reddit.com/r/NixOS/comments/1ab77ht/comment/kjq75jz/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) works for me, and I don't understand why.
> 
> So the gradle opts line probably needs to point to a `build-tools` version that you have installed `GRADLE_OPTS = "-Dorg.gradle.project.android.aapt2FromMavenOverride=${androidSdk}/libexec/android-sdk/build-tools/34.0.0/aapt2"; `
> 
> `buildToolsVersion = "34.0.0"`

I tried this but it didn't work out for me

**Comment by babariviere** [comment]
An issue has been created upstream for this: https://github.com/NixOS/nixpkgs/issues/289936
