### ISSUE TITLE
dart sdk missing

### ISSUE THREAD

**Issue by NANASHI0X74** [babariviere/flutter-nix-hello-world#6]
emacs' lsp-dart seems to search for the dart binary under the path where flutter is located, but it isn't there:
`[LSP Dart] Dart command not found in path ’/nix/store/hiiapmm5f9qr8si2k182v5rq3ix2q64i-flutter-stable-1.17.5/bin/cache/dart-sdk/bin/dart’ [2 times]` 
Am I now to include dart in my shell.nix as well? Doesn't flutter normally bundle a version of dart? If possible, I think that one should be preferred, or not?

**Comment by NANASHI0X74** [comment]
after a bit of searching, I found this: https://github.com/NixOS/nixpkgs/pull/99920 which I suppose will fix this when it's merged

**Comment by babariviere** [comment]
Yes, you are right! I will look at your other PRs, but this issue is not related to this repo!

**Comment by NANASHI0X74** [comment]
https://github.com/NixOS/nixpkgs/issues/98405#issuecomment-712785071
Here's a workaround for the time being
