### ISSUE TITLE
Latest nix version support

### ISSUE THREAD

**Issue by Lzyct** [babariviere/flutter-nix-hello-world#7]
Hi, may you update your nix config with the latest version?
I'm trying to run your project but give me some errors like this

![image](https://user-images.githubusercontent.com/1531684/191419703-cef59913-ce8b-47b1-8f80-57216d3fda70.png)

**Comment by babariviere** [comment]
Hello, sure. I will try to update it to a flake in the process.

**Comment by babariviere** [comment]
Sorry for taking so long, but I finally updated it to the latest version. + I have added the flake.nix as an example.
